In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# Load the dataset
df = pd.read_csv('/content/preformance_prediction.csv')

# Display basic information about the dataset
print(df.shape)
print(df.dtypes)
df.head()

(42000, 8)
Student ID                                      object
Study Hours per Week                            object
Attendance Rate                                float64
Previous Grades                                float64
Participation in Extracurricular Activities     object
Parent Education Level                          object
Passed                                          object
Junk Column                                     object
dtype: object

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed,Junk Column
0,S00001,12.5,NaN,75.0,Yes,Master,Yes,B
1,S00002,9.3,95.3,60.6,No,High School,No,B
2,NaN,13.2,NaN,10.0,No,Associate,NaN,B
3,S00004,17.6,76.8,NaN,Yet,Bachelor,NaN,C
4,S00005,8.8,89.3,72.7,No,Master,NaN,A

# Data Collection and Preprocessing
## Data Cleaning
### Handle messing values
### Remove unwanted Colomns
### Remove Duplicated rows
## Data transformation
### Normalization
## Data splitteing

In [48]:
df = df.drop(columns=['Junk Column'])
df.head()
#Delete Unwanted column

,Student ID,Study Hours per Week,Attendance Rate,Previous Grades,Participation in Extracurricular Activities,Parent Education Level,Passed
0,S00001,12.5,NaN,75.0,Yes,Master,Yes
1,S00002,9.3,95.3,60.6,No,High School,No
2,NaN,13.2,NaN,10.0,No,Associate,NaN
3,S00004,17.6,76.8,NaN,Yet,Bachelor,NaN
4,S00005,8.8,89.3,72.7,No,Master,NaN

In [2]:
df['Study Hours per Week'] = df['Study Hours per Week'].str.replace(r'[^0-9.-]', '', regex=True)
#remove the strings from the numeric columns
df['Study Hours per Week'] = pd.to_numeric(df['Study Hours per Week'], errors='coerce')

df['Study Hours per Week'] = df['Study Hours per Week'].astype(float)
df['Study Hours per Week'].fillna(df['Study Hours per Week'].mean(), inplace=True)
#convert numeric columns to float

NameError: name 'df' is not defined

In [ ]:

data_cleaned = df.drop(columns=['Junk Column'])

# Drop rows with too many missing values
threshold = len(data_cleaned.columns) * 0.6  # Keep rows with at least 60% non-NA values
data_cleaned = data_cleaned.dropna(thresh=threshold)

# Handle categorical inconsistencies (e.g., "Yet" to "Yes")
data_cleaned['Participation in Extracurricular Activities'] = data_cleaned[
    'Participation in Extracurricular Activities'
].replace({'Yet': 'Yes'})

# Impute missing values for numerical columns using median
num_cols = ['Study Hours per Week', 'Attendance Rate', 'Previous Grades']
data_cleaned[num_cols] = data_cleaned[num_cols].fillna(data_cleaned[num_cols].median())

# Drop rows with missing values in categorical columns for simplicity
data_cleaned = data_cleaned.dropna(subset=['Participation in Extracurricular Activities',
                                           'Parent Education Level', 'Passed'])

# Display cleaned data info
cleaned_data_info = {
    "shape": data_cleaned.shape,
    "missing_values": data_cleaned.isnull().sum(),
    "sample_data": data_cleaned.head()
}

cleaned_data_info

TypeError: Cannot convert [['12.5' '9.3' '17.6' ... '13.9' '4.4' nan]] to numeric

In [5]:
f = '13'
f = float(f)
f

13.0